# Generated by Django 4.1 on 2024-09-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='duracao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
